# Generated by Django 3.1.2 on 2020-11-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_category', '0001_initial'),
        ('eshop_products', '0003_auto_20201110_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='eshop_products_category.ProductsCategory', verbose_name='دسته بندی ها'),
        ),
    ]
