# Generated by Django 3.1.2 on 2021-02-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('eshop_products', '0006_product_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='english_title',
            field=models.SlugField(default=None, max_length=150, verbose_name='عنوان انگلیسی', null=True, blank=True),
        ),
    ]
