# Generated by Django 3.1.2 on 2021-02-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0007_product_english_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='english_title',
            field=models.SlugField(default='-', max_length=150, verbose_name='عنوان انگلیسی'),
        ),
    ]
