# Generated by Django 3.1.2 on 2021-02-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0008_auto_20210220_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='english_title',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product1/<function upload_image_path at 0x049887C0>', verbose_name='تصویر محصول'),
        ),
    ]
