# Generated by Django 3.1.2 on 2021-02-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0009_auto_20210220_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product1/<function upload_image_path at 0x03F18F58>', verbose_name='تصویر محصول'),
        ),
    ]
