# Generated by Django 3.1.2 on 2021-04-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0013_usercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
    ]
