# Generated by Django 3.1.2 on 2021-05-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0014_usercomment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='active',
            field=models.BooleanField(default=False, verbose_name='فعال/غیرفعال'),
        ),
    ]
