# Generated by Django 3.1.2 on 2021-03-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0002_auto_20210125_1553'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('eshop_account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userprofile',
        ),
    ]
