# Generated by Django 3.1.2 on 2021-03-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0012_auto_20210303_1813'),
        ('eshop_account', '0004_auto_20210303_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'علاقه مندی', 'verbose_name_plural': 'علاقه مندی ها'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='favorite_product',
            field=models.ManyToManyField(blank=True, null=True, to='eshop_products.Product'),
        ),
    ]
