# Generated by Django 3.1.2 on 2021-03-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account', '0005_auto_20210303_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='curent_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='favorite_product',
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite_product',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
