# Generated by Django 3.1.2 on 2021-03-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account', '0007_auto_20210303_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
    ]
