# Generated by Django 3.1.2 on 2021-01-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان سایت')),
                ('address', models.CharField(max_length=50, verbose_name='ادرس')),
                ('phone', models.CharField(max_length=50, verbose_name='تلفن ')),
                ('mobile', models.CharField(max_length=50, verbose_name='تلفن همراه')),
                ('email', models.EmailField(max_length=50, verbose_name='ایمیل')),
                ('copyright', models.CharField(max_length=50, verbose_name='کپی رایت')),
                ('about_us', models.TextField(verbose_name='درباره سایت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'مدیریت تنظیمات سایت',
            },
        ),
    ]
