# Generated by Django 3.1.2 on 2021-05-02 12:35

from django.db import migrations, models
import eshop.utils


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='logo',
            field=models.ImageField(default=None, height_field=51, null=True, upload_to=eshop.utils.upload_image_path, verbose_name='تصویر لکو سایت', width_field=180),
        ),
    ]
