# Generated by Django 3.1.2 on 2021-01-25 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0005_productgallery'),
        ('eshop_sliders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop_products.product'),
        ),
    ]
