# Generated by Django 3.1.2 on 2021-01-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sliders', '0002_slider_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.URLField(max_length=100, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='عنوان'),
        ),
    ]
