# Generated by Django 3.1.2 on 2021-02-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sliders', '0004_auto_20210216_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='english_title',
            field=models.SlugField(blank=True, default=None, max_length=150, null=True, verbose_name='عنوان انگلیسی'),
        ),
    ]
