# Generated by Django 3.1.2 on 2021-02-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sliders', '0005_slider_english_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='english_title',
            field=models.SlugField(blank=True, default='-', max_length=150, null=True, verbose_name='عنوان انگلیسی'),
        ),
    ]
